//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Praksa5
{
    using System;
    using System.Collections.Generic;
    
    public partial class MESTO
    {
        public int Sifra_Mesto { get; set; }
        public string Naziv_Mesto { get; set; }
    }
}
