//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Praksa5
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Praksa5Entities : DbContext
    {
        public Praksa5Entities()
            : base("name=Praksa5Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MESTO> MESTO { get; set; }
        public virtual DbSet<ZAPOSLENI> ZAPOSLENI { get; set; }
    
        public virtual int sp_delete_zaposleni(Nullable<long> maticni_Broj)
        {
            var maticni_BrojParameter = maticni_Broj.HasValue ?
                new ObjectParameter("Maticni_Broj", maticni_Broj) :
                new ObjectParameter("Maticni_Broj", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_delete_zaposleni", maticni_BrojParameter);
        }
    }
}
