//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Praksa5
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZAPOSLENI
    {
        public long Maticni_Broj_Zaposlenog { get; set; }
        public string Prezime_Zaposlenog { get; set; }
        public string Ime_Zaposlenog { get; set; }
        public string Ime_Jednog_Roditelja { get; set; }
        public string Adresa { get; set; }
        public Nullable<int> Sifra_Mesto { get; set; }
        public string Email { get; set; }
    }
}
